require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.cmp"
-- require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
-- require "user.autopairs"
require "user.comment"
-- require "user.gitsigns"
require "user.nvim-tree"
<<<<<<< HEAD
-- require "user.bufferline"
=======
require "user.bufferline"
>>>>>>> ade556a ([upd] Updated init.lua and added new plugin)
-- require "user.lualine"
require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
-- require "user.alpha"
require "user.whichkey"
-- require "user.autocommands"
